#pragma once

#define GOPHER_VERSION_MAJOR 1
#define GOPHER_VERSION_MINOR 0
#define GOPHER_VERSION_PATCH 1
#define GOPHER_VERSION_BUILD 0
#define GOPHER_VERSION_STRING "1.0.1.0"
#define GOPHER_VERSION_DISPLAY "1.0.1"
